// Authentication types
export type {
  User,
  SessionData,
  AuthState,
  LoginCredentials,
  SignupData,
  ProviderName,
  SocialAuthData,
  OAuthCallbackData,
  AuthResponse,
  LoginResponse,
  SignupResponse,
  SocialAuthResponse,
  AuthError,
  Connection,
  ProviderUser,
  MobileAuthState,
  MobileLoginCredentials,
  MobileSignupData,
  AuthApiConfig,
  SessionStorage,
  AuthContextType,
  VerificationData,
  TwoFactorData,
  EnhancedAuthResponse,
} from './src/auth.js'

// API types
export type {
  ApiResponse,
  PaginatedResponse,
  ApiError,
  HttpMethod,
  RequestConfig,
  AuthApiEndpoints,
  LoginRequest,
  LoginApiResponse,
  JWTLoginApiResponse,
  SignupRequest,
  SignupApiResponse,
  VerifyRequest,
  VerifyApiResponse,
  OnboardingRequest,
  OnboardingApiResponse,
  JWTOnboardingApiResponse,
  SocialAuthRequest,
  SocialAuthApiResponse,
  OAuthCallbackRequest,
  OAuthCallbackApiResponse,
  JWTOAuthCallbackApiResponse,
  RefreshApiResponse,
  JWTRefreshApiResponse,
  LogoutApiResponse,
  VerificationRequest,
  VerificationApiResponse,
  ForgotPasswordRequest,
  ForgotPasswordApiResponse,
  ResetPasswordRequest,
  ResetPasswordApiResponse,
  NetworkError,
  RateLimitResponse,
  BotDetectionResponse,
  ValidationErrorResponse,
  ServerErrorResponse,
} from './src/api.js'

// Organization types
export type {
  Organization,
  OrganizationRole,
  UserOrganization,
  OrganizationsApiResponse,
  OrganizationsApiError,
} from './src/organization.js'