name = "epic-startup"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

[vars]
PUBLIC_ROOT_APP = "zama-887.workers.dev"

[[d1_databases]]
binding = "DB"
database_name = "web-cms-db"
database_id = "3085ac9c-03bd-403c-b6b9-d06efabbace8"

[[r2_buckets]]
binding = "MEDIA_BUCKET"
bucket_name = "web-media"

[env.production]
name = "epic-startup"

[env.preview]
name = "epic-startup-preview"

[env.staging]
name = "epic-startup-staging"

# [[kv_namespaces]]
# binding = "SESSION"
# id = "your-kv-namespace-id"
# preview_id = "your-preview-kv-namespace-id"